global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ecosmart-gateway'
    static_configs:
      - targets: ['gateway:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'ecosmart-web'
    static_configs:
      - targets: ['web:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
